#! /bin/sh

# Open sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar
$HOME/.config/polybar/launch.sh

# set up the two monitors for bspwm
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1-0')
if [[ $my_laptop_external_monitor = *disconnected* ]]; then
	bspc monitor eDP1 -d 1 2 3 4 5 6
else
	if [[ $my_laptop_external_monitor = *connected* ]]; then
		bspc monitor HDMI-1-0 -d 1 2
		bspc monitor eDP1 -d 3 4 5 6
		bspc monitor HDMI-1-0 -s eDP1 
	else
		bspc monitor eDP1 -d 1 2 3 4 5 6
	fi
fi

# to fine class: xprop | grep 'CLASS'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a pick-colour-picker state=floating
bspc rule -a Pick-colour-picker state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Peek state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Nvidia-settings state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=tiled
bspc rule -a UnityHub state=floating
bspc rule -a Godot_Engine state=floating
bspc rule -a piloto_2d state=floating

bspc config normal_border_color "#19121f"
bspc config focused_border_color #6ebfda
